Repository kleenex1/cheers, pull requests merged in 2022-11, with the labels that each got.

#2 #1 FEAT: 유저모델생성
  cheers/models.py
  config/settings.py
Labels: 💻 기능 구현

#8 #7 FEAT: 오픈그래프 카드 생성
  images/images/Cheers _오픈그래프.PNG
  images/images/favicon -.ico
  templates/main.html
Labels: 💻 기능 구현

#12 #9 FEAT: HEADER 생성
  templates/main.html
Labels: 💻 기능 구현

#42 #37 STYLE: Recipe Form html수정
  cheers/templates/cheers/index.html
  cheers/templates/cheers/recipe_form.html
  cheers/views.py
Labels: 🪄 수정

#44 #39 FEAT: 메인페이지 공지사항 구현
  static/js/main.js
  templates/main.html
Labels: 💻 기능 구현

#46 #45 FEAT: PROMOTION 구현
  templates/main.html
Labels: 💻 기능 구현

#48 #47 FEAT: PROMOTION 수정
  templates/main.html
Labels: 🪄 수정

#50 #49 FEAT: cocktails and special stories 구현
  templates/main.html
Labels: 💻 기능 구현

#52 #43 FEAT: Recipe 수정, 삭제페이지
  cheers/templates/cheers/recipe_confirm_delete.html
  cheers/templates/cheers/recipe_detail.html
  cheers/templates/cheers/recipe_form.html
  cheers/urls.py
  cheers/views.py
Labels: 💻 기능 구현

#53 #51 FEAT: 서비스 홍보 BANNER 구현
  templates/main.html
Labels: 💻 기능 구현

#56 #55 FEAT: 메인페이지 RECIPE 구현
  templates/main.html
Labels: 💻 기능 구현

#63 #62 FEAT: 메인페이지 수정
  .vscode/settings.json
  templates/main.html
Labels: 🪄 수정

#68 #67 FEAT: 프로필 페이지
  cheers/admin.py
  cheers/migrations/0005_auto_20221116_1116.py
  cheers/models.py
  cheers/templates/cheers/index.html
  cheers/templates/cheers/profile.html
  cheers/templates/cheers/recipe_detail.html
  cheers/urls.py
  cheers/views.py
Labels: 💻 기능 구현

#73 #72 FEAT: 칵테일 디테일 페이지 레이아웃 구현
  templates/recipe.html
Labels: 💻 기능 구현

#77 #75 FEAT: Model 추가(좋,댓,팔로우)
  cheers/admin.py
  cheers/migrations/0006_comment.py
  cheers/migrations/0007_user_following.py
  cheers/migrations/0008_like.py
  cheers/migrations/0009_user_following_blank.py
  cheers/models.py
Labels: 💻 기능 구현

#83 #80 FEAT: related_query_name추가
  cheers/models.py
Labels: 🧹 개선사항

#90 #89 FEAT: 팔로우 기능,페이지 추가
  cheers/templates/cheers/follower_list.html
  cheers/templates/cheers/following_list.html
  cheers/templates/cheers/profile.html
  cheers/urls.py
  cheers/views.py
Labels: 💻 기능 구현
